# Generated by Django 2.2.9 on 2023-02-13 14:45

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=models.TextField(validators=[users.validators.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, validators=[users.validators.validate_not_empty]),
        ),
    ]
